language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t prod-ready-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true prod-ready-react-app npm run test
