language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t prod-ready-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true prod-ready-react-app npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "prod-ready-react-app"
  env: "ProdReadyReactApp-env"
  bubcket_name: "elasticbeanstalk-us-east-1-837062711494"
  bucket_path: "prod-ready-react-app"
  on:
    branch: master
  access_key_id: $acess_key_id
  secret_access_key: $secret_access_key